/**
 * MAPA PAPEL → PERMISSÕES — Single Source of Truth em código.
 *
 * GERADO A PARTIR DE docs/security/rbac.md §4. Não editar à mão sem atualizar
 * a matriz nesse documento: o teste `permissions.matrix.test.ts` compara os dois
 * e falha se divergirem.
 *
 * Decisões: ADR-008 (permissões em código) · ADR-009 (11 papéis).
 */

export const ROLES = [
  'OWNER',
  'ADMIN',
  'FINANCE_MANAGER',
  'PRODUCER',
  'PHOTOGRAPHER',
  'VIDEOGRAPHER',
  'EDITOR',
  'CONTENT_MANAGER',
  'SALES',
  'STAFF',
  'CLIENT',
] as const;
export type Role = (typeof ROLES)[number];

export const PERMISSIONS = [
  'org:read',
  'org:update',
  'org:delete',
  'user:read',
  'user:invite',
  'user:update',
  'user:change_role',
  'user:deactivate',
  'user:reset_mfa',
  'session:revoke_any',
  'lead:read',
  'lead:create',
  'lead:update',
  'lead:assign',
  'lead:delete',
  'client:read',
  'client:create',
  'client:update',
  'client:delete',
  'proposal:read',
  'proposal:create',
  'proposal:send',
  'proposal:delete',
  'booking:read',
  'booking:create',
  'booking:update',
  'booking:confirm',
  'booking:cancel',
  'booking:reschedule',
  'production:read',
  'production:update',
  'production:assign',
  'resource:read',
  'resource:manage',
  'availability:manage',
  'invoice:read',
  'invoice:create',
  'invoice:issue',
  'invoice:void',
  'payment:read',
  'payment:refund',
  'payment:override',
  'ledger:read',
  'reconciliation:run',
  'price:read',
  'price:manage',
  'deliverable:read',
  'deliverable:create',
  'deliverable:publish',
  'deliverable:delete',
  'file:upload',
  'file:download',
  'file:delete',
  'content:read',
  'content:create',
  'content:publish',
  'content:delete',
  'campaign:read',
  'campaign:create',
  'campaign:update',
  'campaign:launch',
  'post:read',
  'post:create',
  'post:approve',
  'post:publish',
  'project:read',
  'project:create',
  'project:update',
  'project:deploy',
  'domain:manage',
  'audit:read',
  'analytics:read',
  'analytics:financial',
] as const;
export type Permission = (typeof PERMISSIONS)[number];

/** `full` = permissão plena · `owned` = apenas registos próprios ou atribuídos (🔒) */
export interface RoleGrants {
  readonly full: readonly Permission[];
  readonly owned: readonly Permission[];
}

export const ROLE_PERMISSIONS: Readonly<Record<Role, RoleGrants>> = {
  OWNER: {
    full: [
      'org:read',
      'org:update',
      'org:delete',
      'user:read',
      'user:invite',
      'user:update',
      'user:change_role',
      'user:deactivate',
      'user:reset_mfa',
      'session:revoke_any',
      'lead:read',
      'lead:create',
      'lead:update',
      'lead:assign',
      'lead:delete',
      'client:read',
      'client:create',
      'client:update',
      'client:delete',
      'proposal:read',
      'proposal:create',
      'proposal:send',
      'proposal:delete',
      'booking:read',
      'booking:create',
      'booking:update',
      'booking:confirm',
      'booking:cancel',
      'booking:reschedule',
      'production:read',
      'production:update',
      'production:assign',
      'resource:read',
      'resource:manage',
      'availability:manage',
      'invoice:read',
      'invoice:create',
      'invoice:issue',
      'invoice:void',
      'payment:read',
      'payment:refund',
      'payment:override',
      'ledger:read',
      'reconciliation:run',
      'price:read',
      'price:manage',
      'deliverable:read',
      'deliverable:create',
      'deliverable:publish',
      'deliverable:delete',
      'file:upload',
      'file:download',
      'file:delete',
      'content:read',
      'content:create',
      'content:publish',
      'content:delete',
      'campaign:read',
      'campaign:create',
      'campaign:update',
      'campaign:launch',
      'post:read',
      'post:create',
      'post:approve',
      'post:publish',
      'project:read',
      'project:create',
      'project:update',
      'project:deploy',
      'domain:manage',
      'audit:read',
      'analytics:read',
      'analytics:financial',
    ],
    owned: [

    ],
  },
  ADMIN: {
    full: [
      'org:read',
      'org:update',
      'user:read',
      'user:invite',
      'user:update',
      'user:change_role',
      'user:deactivate',
      'session:revoke_any',
      'lead:read',
      'lead:create',
      'lead:update',
      'lead:assign',
      'lead:delete',
      'client:read',
      'client:create',
      'client:update',
      'proposal:read',
      'proposal:create',
      'proposal:send',
      'proposal:delete',
      'booking:read',
      'booking:create',
      'booking:update',
      'booking:confirm',
      'booking:cancel',
      'booking:reschedule',
      'production:read',
      'production:update',
      'production:assign',
      'resource:read',
      'resource:manage',
      'availability:manage',
      'invoice:read',
      'invoice:create',
      'invoice:issue',
      'payment:read',
      'ledger:read',
      'reconciliation:run',
      'price:read',
      'price:manage',
      'deliverable:read',
      'deliverable:create',
      'deliverable:publish',
      'deliverable:delete',
      'file:upload',
      'file:download',
      'file:delete',
      'content:read',
      'content:create',
      'content:publish',
      'content:delete',
      'campaign:read',
      'campaign:create',
      'campaign:update',
      'campaign:launch',
      'post:read',
      'post:create',
      'post:approve',
      'post:publish',
      'project:read',
      'project:create',
      'project:update',
      'project:deploy',
      'domain:manage',
      'audit:read',
      'analytics:read',
      'analytics:financial',
    ],
    owned: [

    ],
  },
  FINANCE_MANAGER: {
    full: [
      'client:read',
      'client:update',
      'proposal:read',
      'booking:read',
      'booking:create',
      'booking:confirm',
      'booking:cancel',
      'invoice:read',
      'invoice:create',
      'invoice:issue',
      'invoice:void',
      'payment:read',
      'payment:refund',
      'payment:override',
      'ledger:read',
      'reconciliation:run',
      'price:read',
      'price:manage',
      'campaign:read',
      'project:read',
      'audit:read',
      'analytics:read',
      'analytics:financial',
    ],
    owned: [

    ],
  },
  PRODUCER: {
    full: [
      'client:read',
      'booking:read',
      'booking:create',
      'booking:update',
      'booking:confirm',
      'booking:cancel',
      'booking:reschedule',
      'production:read',
      'production:update',
      'production:assign',
      'resource:read',
      'resource:manage',
      'availability:manage',
      'price:read',
      'deliverable:read',
      'deliverable:create',
      'deliverable:publish',
      'file:upload',
      'file:download',
      'project:read',
      'project:update',
      'analytics:read',
    ],
    owned: [

    ],
  },
  PHOTOGRAPHER: {
    full: [
      'resource:read',
    ],
    owned: [
      'client:read',
      'booking:read',
      'production:read',
      'production:update',
      'availability:manage',
      'deliverable:read',
      'deliverable:create',
      'file:upload',
      'file:download',
    ],
  },
  VIDEOGRAPHER: {
    full: [
      'resource:read',
    ],
    owned: [
      'client:read',
      'booking:read',
      'production:read',
      'production:update',
      'availability:manage',
      'deliverable:read',
      'deliverable:create',
      'file:upload',
      'file:download',
    ],
  },
  EDITOR: {
    full: [
      'resource:read',
    ],
    owned: [
      'client:read',
      'booking:read',
      'production:read',
      'production:update',
      'deliverable:read',
      'deliverable:create',
      'file:upload',
      'file:download',
      'project:read',
      'project:update',
    ],
  },
  CONTENT_MANAGER: {
    full: [
      'lead:read',
      'lead:create',
      'file:upload',
      'content:read',
      'content:create',
      'content:publish',
      'campaign:read',
      'campaign:create',
      'campaign:update',
      'campaign:launch',
      'post:read',
      'post:create',
      'post:approve',
      'post:publish',
      'analytics:read',
    ],
    owned: [

    ],
  },
  SALES: {
    full: [
      'lead:read',
      'lead:create',
      'lead:update',
      'lead:assign',
      'client:read',
      'client:create',
      'client:update',
      'proposal:read',
      'proposal:create',
      'proposal:send',
      'booking:read',
      'booking:create',
      'booking:update',
      'resource:read',
      'invoice:read',
      'price:read',
      'content:read',
      'campaign:read',
      'post:read',
      'project:read',
      'project:create',
      'analytics:read',
    ],
    owned: [

    ],
  },
  STAFF: {
    full: [
      'resource:read',
    ],
    owned: [
      'client:read',
      'booking:read',
      'production:read',
      'production:update',
      'deliverable:read',
      'file:upload',
      'file:download',
    ],
  },
  CLIENT: {
    full: [

    ],
    owned: [
      'client:read',
      'client:update',
      'proposal:read',
      'booking:read',
      'booking:create',
      'booking:cancel',
      'invoice:read',
      'payment:read',
      'deliverable:read',
      'file:download',
      'project:read',
    ],
  },
} as const;

/** Papéis cujo acesso é sempre limitado ao que lhes pertence ou foi atribuído. */
export const SCOPED_ROLES: readonly Role[] = [
  'PHOTOGRAPHER', 'VIDEOGRAPHER', 'EDITOR', 'STAFF', 'CLIENT',
] as const;

/** Papéis com acesso ao back-office. `CLIENT` nunca entra em /admin. */
export const STAFF_ROLES: readonly Role[] = ROLES.filter((r) => r !== 'CLIENT');

/** Permissões financeiras — nenhum papel operacional pode ter qualquer uma. */
export const FINANCIAL_PERMISSIONS: readonly Permission[] = PERMISSIONS.filter((p) =>
  ['invoice', 'payment', 'ledger', 'reconciliation', 'price'].includes(p.split(':')[0] ?? ''),
);

export function isPermission(value: string): value is Permission {
  return (PERMISSIONS as readonly string[]).includes(value);
}

export function isRole(value: string): value is Role {
  return (ROLES as readonly string[]).includes(value);
}
